### ISSUE TITLE
php 5.x.x и apache 2.2

### ISSUE THREAD

**Issue by VictorFilimonov** [OSPanel/OpenServerPanel#10]
Товарищи! Верните, пожалуйста, эти версии пыха и апача! Очень требуются!
Много проектов нереально адаптировать под 7 и 8.
Две версии оспанела держать не хочется

**Comment by OSPanel** [comment]
Наша внутренняя политика позволяет нам добавлять в набор только стабильные версии модулей. Разработчики языка PHP в своё время отказались вносить исправления из-за которых происходит периодический APPCRASH в Windows в PHP версий ниже чем 7.1, т.к. эти версии PHP больше не поддерживаются. Но даже PHP 7.1 была исключена из состава программного комплекса по причине нестабильной работы уже в результате наших собственных тестов.

Вы можете добавить любые нужные вам модули самостоятельно, в этом нет ничего сложного, вот [инструкция](https://github.com/OSPanel/OpenServerPanel/wiki/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F#%D0%BA%D0%B0%D0%BA-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D0%B8).

**Comment by OSPanel** [comment]
Наша внутренняя политика позволяет нам добавлять в набор только стабильные версии модулей. Разработчики языка PHP в своё время отказались вносить исправления из-за которых происходит периодический APPCRASH в Windows в PHP версий ниже чем 7.1, т.к. эти версии PHP больше не поддерживаются. Но даже PHP 7.1 была исключена из состава программного комплекса по причине нестабильной работы уже в результате наших собственных тестов.

Вы можете добавить любые нужные вам модули самостоятельно, в этом нет ничего сложного, вот [инструкция](https://github.com/OSPanel/OpenServerPanel/wiki/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F#%D0%BA%D0%B0%D0%BA-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D0%B8).
