### ISSUE TITLE
Feature request: возможность кастомизированной группировки доменов в подменю

### ISSUE THREAD

**Issue by LoranRendel** [OSPanel/OpenServerPanel#14]
Прошу сделать возможным ручную группировку доменов в контекстом меню OSPanel по подменю разного уровня вложенности, например, следующим образом в `project.ini`:

```
[full-example.local]
submenu = Example projects
```
```
[example.com]
submenu = Work projects\Other
```

Это удобно, когда есть много сайтов, которые можно сгруппировать по типам, работодателю итд.

**Comment by OSPanel** [comment]
Добавлена опция category для секции проекта в project.ini. Но уровень будет только один, подкатегорий не будет.

```
[a.com]

[b.local]

[c.net]

[x.net]
category = ОАО Ромашка

[y.net]
category = ИП Иванов

[z.net]
category = Диплом
```

При группировке по доменной зоне главное меню проектов будет выглядеть так:

![image](https://github.com/OSPanel/OpenServerPanel/assets/93676052/4c717df5-012f-4f42-8e54-5ad586400046)
