### ISSUE TITLE
На столько сырой проект, что выкатывать его просто нельзя было!

### ISSUE THREAD

**Issue by pticun** [OSPanel/OpenServerPanel#16]
Базовые модули php, nginx и половина вспомогательных не запускается на давней системе. На нулевой системе без проблем. Что говорит о недостаточности настроек установочного процесса. Логирование на нуле... 
[2024-05-17 10:39:07] | Модуль: PHP-8.1 (default)
[2024-05-17 10:39:07] | Объект: PID 3076
[2024-05-17 10:39:07] | Код выхода/ошибки: 1
[2024-05-17 10:39:07] | Сообщение: Работа модуля приостановлена
[2024-05-17 10:39:07] | Причина: Рабочий процесс модуля неожиданно завершил свою работу
Это что? Логирование?
--------------------------------------------------------------------------------------------
[2024-05-17 10:39:05] Running PHP-8.1 (default)
--------------------------------------------------------------------------------------------
(OS 10013)Сделана попытка доступа к сокету методом, запрещенным правами доступа.  : AH00072: make_sock: could not bind to address 127.127.126.32:443
AH00451: no listening sockets available, shutting down
AH00015: Unable to open logs
Или это??

Нет веб интерфейса, что делает работу с таким сырым продуктом просто невыносимым. Это не среда linux, это Windows, здесь, чтобы понять проблему и её устранить потребуются дни с открытием миллиона файлов лога и настройки по документации (очень грязно расписанной) и уж тем более взаимодействие с рабочей средой. 
Откатывайте!

**Comment by delphinpro** [comment]
ниасилил =)

**Comment by pticun** [comment]
> ниасилил =)

Дело не в том что я не осилил работу с этим сырым продуктом, а в том, что пришлось изобретать велосипед, чтобы подключить на "захламленной" системе сие чудо. Как например nginx не садится без точно свободного 443 порта (что является упущением разработчика). Как понимает любой школьник, 443 порт будет занят при использовании мало-мальски полезного софта, например как у меня вмваря стояла. И вместо прописи свободного порта годного под Nginx при установке софта, этот момент игнорируется. Также как порт 80 и т.д.

Работа с БД на основе мускула вообще становится невозможна для пользователей уровня ниже среднего, т.к. той же самой phpmyadmin не вшито даже на стадии консоли.

И это то, что я нашел за 20 минут после установки продукта.


Так что твой комментарий отсталого дегенерата, который даже не попробовал "асилить" все вышесказанное мной.

**Comment by delphinpro** [comment]
Во-первых, если вам нужно менять стандартные порты, значит вы должны быть чуть более подкованы в теме, нежели начинающий.

Во-вторых, поменять порты можно, об этом есть инфа как минимум на форуме.

В-третьих, этот раздел на гитхабе предназначен для сообщения о проблемах и ошибках самого OpenServer'a, а не для жалоб. Ваш пост был бы уместен на форуме программы. https://ospanel.io/forum

**Comment by pticun** [comment]
Теперь уже ближе к теме пошел разговор. 
Именно об этом речь. Что проблема существует на стадии выпуска продукта, предназначенного для использования в среде Windows, а не иных, где смена порта (в том числе) гораздо более простой процесс, нежели в Windows, которая изначально предназначена для пользователей среднего уровня и ниже. Проект Open Server - проект также для начального уровня, позиционировался всегда! А темпов развития (что, конечно, в свою очередь похвально) не хватает, чтобы превзойти иные продукты, которые как раз и созданы как среды для разработки продвинутого уровня. Поэтому мой комментарий поможет найти ответ на вопрос "почему не работает?" и "как с этим работать?" для пользователей, кто только начал работу и изучение именно на гит, а не не в толмуте постов на форуме продукта.
