### ISSUE TITLE
Ошибка планировщика задач

### ISSUE THREAD

**Issue by GrozaZool** [OSPanel/OpenServerPanel#17]
> В колонках 6-7 могут находится только числа и символ *
> включение/выключение задания ( * или 1 - включено, 0 - выключено )

Либо ошибка в доке, либо в коде. Планировщик падает, если указать 7 колонку крона как *. Если указать число - работает.

../logs/scheduler.txt: Сообщение: Недопустимое значение плана выполнения задания

**Comment by OSPanel** [comment]
Исправление готово и будет доступно в ближайшем обновлении. До выхода обновления исправленный исполняемый файл программы можно скачать здесь: https://files.ospanel.io/ospanel.exe

**Comment by GrozaZool** [comment]
@OSPanel файл заменил.

Стандартная команда из доки:

> Резервное копирование   = */5 * * * * 1 1    "%COMSPEC%" /c "tar -czf {base_dir}\.osp\backup\{host_decoded}.tar.gz -C {public_dir} *"

падает с ошибкой 
[2024-05-20 00:50:00] | Сообщение: Не удалось запустить задание
[2024-05-20 00:50:00] | Причина: Параметр задан неверно
