### ISSUE TITLE
Урезание наименования системных переменных

### ISSUE THREAD

**Issue by Ink0gnit0** [OSPanel/OpenServerPanel#21]
Заметил такую особенность. Урезается наименование системной переменной, следующей за системной переменной **ESC**:

![0129481290841902841092840912](https://github.com/OSPanel/OpenServerPanel/assets/1517426/ef765fc6-6a80-4bdc-87ae-89185ee903ae)

Должно быть **ES_HOME**, а в окружение попадает **S_HOME**.

Костыльно решается изменением переменной **ESC** на **_X_ESC** в шаблоне [КОРЕНЬ_OSP6]\system\templates\**osp.bat**.

**Comment by OSPanel** [comment]
Ничего не урезается. Это особенности отображения в консоли.
