### ISSUE TITLE
Access-Control-Allow-Origin contains multiple values

### ISSUE THREAD

**Issue by hungnc89** [OSPanel/OpenServerPanel#22]
![image](https://github.com/OSPanel/OpenServerPanel/assets/72601287/8c866a21-d2a4-4364-ab1c-0a915696980c)

- version : 6.0.0
- php : all php versions
- nginx : do not use

![image](https://github.com/OSPanel/OpenServerPanel/assets/72601287/aa114a5c-0fdc-4d5a-a727-cc32a926c9c4)

I am using ospanel 6.0.0 and I am experiencing issues with sending AJAX requests, causing the browser to encounter CORS errors.

The browser notice issue : Access to fetch at 'http://waterfalls.local/api/v1/user/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Sorry if I wrong.

**Comment by delphinpro** [comment]
The "Access-Control-Allow-Origin" header is already registered in Apache configurations for all versions of PHP.
If you add a header in your scripts, you will get a duplicate.
Try to edit the `config/.../httpd.conf` file according to your needs.

**Comment by hungnc89** [comment]
Thank you, as you suggested, I tried removing the allowed origins in my Laravel project, and it worked fine. This behavior is different from version 5 when I configured it with Nginx.
