### ISSUE TITLE
Не работает из Корня диска.

### ISSUE THREAD

**Issue by korenevskiy** [OSPanel/OpenServerPanel#29]
Прежде писал что не работает из RAMдиска. 
Прошло время, решился перейти на новую версию еще раз.
Устанавливаю OSPanel в корень RAMдиска.
НЕ РАБОТАЕТ!!!

Очевидно же что я начал грешить OSPanel в RAMдиске. При том что прежняя версия OSPanel работает RAMдиске в корне.
Провёл тесты, оказалось что проблема именно корне диска.

При разных вариантах установки портативной версии и обычной. 
Оказывается оба варианта в корне диска не хотят работать.

На обычный диск в корень НЕ проверял.

**Comment by OSPanel** [comment]
Проблема известная и уже давно исправлена. Исправление будет включено в ближайшее обновление программы.

**Comment by korenevskiy** [comment]
> Проблема известная и уже давно исправлена. Исправление будет включено в ближайшее обновление программы.

Подскажите пожалуйста, приблизительно примерно когда будет обновление?

**Comment by delphinpro** [comment]
Фикс доступен уже сейчас. Посмотрите на форуме тему "Решение известных проблем".
