### ISSUE TITLE
Nginx + PHP(Apache) предложение по стандартному конфигу

### ISSUE THREAD

**Issue by SagePtr** [OSPanel/OpenServerPanel#33]
По дефолту [virtual_proxied_host.conf](https://github.com/OSPanel/OpenServerPanel/blob/main/modules/Nginx-1.27/conf/virtual_proxied_host.conf) следующий:
```
    location / {
        try_files $uri $uri/ =404;
        # try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ [^/]\.php(/|$) {
        proxy_cache_bypass    $http_upgrade;
        proxy_http_version    1.1;
        proxy_pass            http://$php_server:80;
        proxy_set_header      Connection $connection_upgrade;
        proxy_set_header      Host $host;
        proxy_set_header      Upgrade $http_upgrade;
        proxy_set_header      X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto $scheme;
        proxy_set_header      X-Real-IP $remote_addr;
        # proxy_set_header    X-Country-Code $geoip2_data_country_code;
        # proxy_set_header    X-Country-Name $geoip2_data_country_name;
    }
```
Но в этом конфиге не учитывается важный аспект: не перенаправляются запросы 404 на Апач, как это типично делают в этой связке для того, чтобы задействовать правила mod_rewrite из .htaccess без необходимости ручной правки конфигов Nginx.
Конечно, можно и руками настроить Nginx и перенаправлять, но дефолтное проксирование не найденных файлов (а не только файлов php) на апач избавит от лишних телодвижений и множества тем на форуме а-ля "Помогите настроить маршруты Laravel".
Заранее спасибо.

**Comment by OSPanel** [comment]
https://github.com/OSPanel/OpenServerPanel/commit/0c35fa46bc39d7681d39f69eb27de3b3a55b3c91
