### ISSUE TITLE
Cron / Schedule / Расписание Ошибка запуска

### ISSUE THREAD

**Issue by AEDevSolutions** [OSPanel/OpenServerPanel#34]
Скопировал полностью из доки. Проверил, вроде все ок по синтаксису. Но выдает ошибку
![image](https://github.com/OSPanel/OpenServerPanel/assets/51477611/931f1089-26dd-434b-8579-5819da2c026e)

При этом запустил команду в терминале и она успешно отработала
![image](https://github.com/OSPanel/OpenServerPanel/assets/51477611/a54abdb2-2a92-4dd9-a818-0faef42fec1b)

**Comment by OSPanel** [comment]
https://github.com/OSPanel/OpenServerPanel/issues/17
