### ISSUE TITLE
В трее сделать подменю - включенные модули.

### ISSUE THREAD

**Issue by russeljo** [OSPanel/OpenServerPanel#38]
Сейчас необходимо заходить в каждый модуль-подмодуль, чтобы увидеть какая версия включена.
Удобнее было бы иметь один общий список всех включенных модулей - удобнее смотреть, перезапускать. 
В идеале конечно некий диспетчер процессов(задач).

**Comment by OSPanel** [comment]
1. Отключите группировку модулей по категории и отключите отображение модулей в подменю. Так, вам не придётся открывать подгруппы и вы сможете сразу видеть какие модули включены.
2. Нет, отдельный список включённых модулей не будет удобнее того списка, который есть. Мы не планируем делать отдельный список.
3. Такой диспетчер есть - выполните команду osp modules или osp status в консоли программы.
