### ISSUE TITLE
Некоторые домены не попадают в файл hosts и сайт не открывается. 

### ISSUE THREAD

**Issue by AEDevSolutions** [OSPanel/OpenServerPanel#39]
Есть проект. После сборки он складывается в папку dist. Но он не открывается в браузере. Начал искать. В списке проектов, он есть. Ошибок нет. Но он не добавлен в файл hosts. Остальные 30+доменов есть.
![image](https://github.com/user-attachments/assets/db9898a1-119a-4a02-9111-8a77835dd371)
![image](https://github.com/user-attachments/assets/6f0e69c5-a0bc-4654-9618-0d5931ebd6bd)
![image](https://github.com/user-attachments/assets/3e611f88-1984-4180-8885-de3e731b1859)
![image](https://github.com/user-attachments/assets/a6ca46cd-946d-4abc-906c-37b94c858e89)

я попробовал временно добавить его в hosts. но он не открывает сайт, а просто заглушку "Как Вы сюда попали?"

Может есть идеи?

UPDATE
Я не знаю, как это работает, но после того, как я включил для домена nginx, то оно добавило в hosts и оно заработало. Почему такое поведение?

UPDATE 2
На этом история не закончилось. Мне понадобилось, чтобы он был доступен из вне. В других проектах я просто указал локальный ip, на который проброшен роутер. Но я получаю ошибку при старте
![image](https://github.com/user-attachments/assets/f63c55a4-7f9d-414f-ac79-794981351ff3)
![image](https://github.com/user-attachments/assets/9e57ebd4-7862-487c-9118-5d4f51f089e4)

**Comment by OSPanel** [comment]
Для того, чтобы домен заработал, для него должен быть назначен модуль веб-сервера. Если модуль веб-сервера у вас не запускается, то смотрите причину в логах модуля или в логах этого домена, а не в общем логе программы.
