### ISSUE TITLE
Прописывание ip на уровне конфига проекта в более, чем 1 проекте, ломает запуск веб сервера.

### ISSUE THREAD

**Issue by AEDevSolutions** [OSPanel/OpenServerPanel#40]
Есть необходимость сделать некоторые (не все) сайты доступные из вне. 
Для этого в проекте прописал ip. Заработало из вне. После добавления такого же ip веб-сервер не запускается. Говорит, что порт уже занят.

Есть варианты решения такого кейса?

![image](https://github.com/user-attachments/assets/b6b480d7-4e31-4c8b-9f43-8beecb526560)
![image](https://github.com/user-attachments/assets/2be93fe8-362c-4358-8629-a55f990431a8)
![image](https://github.com/user-attachments/assets/012759b9-b272-48c8-9ded-e8dd309c22e8)

**Comment by AEDevSolutions** [comment]
Из того, что я понял:
1. Если хочешь внешний доступ на локальный ip все делать с одним веб сервером. Либо Nginx, либо Apache. Если ты юзаешь Apache, и тебе в проекте не надо PHP, то ты все равно его должен включить, чтобы у тебя включился Apache.
2. Если все же надо, чтобы был в разных проектах и Apache и Nginx, то можно на сетевую карту добавить несколько ip и пробросить с модема на каждый из них доступ из вне.

**Comment by OSPanel** [comment]
При одинаковых IP в настройках проектов, но при разных модулях веб-сервера, оба модуля веб-сервера пытаются занять одну и ту же пару IP:ПОРТ, что невозможно. Вы создаёте невозможную конфигурацию, что не является багом.
