### ISSUE TITLE
Запуск команды (.bat) после старта и остановки сервера

### ISSUE THREAD

**Issue by garfildalex6** [OSPanel/OpenServerPanel#43]
Добрый день. Спасибо большое за ваш продукт! Подскажите, как запускать определенные команды после старта сервера и после остановки сервера, как это было сделано в 5-й версии сервера?

**Comment by delphinpro** [comment]
В текущей версии такая возможность отсутствует, насколько я знаю.

**Comment by garfildalex6** [comment]
Я в документации видел в настройках глобальных и проекта "start_command". Я хотел ее использовать, хотя бы для запуска , но почему-то она не не работает, если ввожу туда команду cmd. 
Подскажите, пожалуйста, почему?
