### ISSUE TITLE
How to upgrade mysql version to 8.0 on Win 11

### ISSUE THREAD

**Issue by giakhanh22024558** [OSPanel/OpenServerPanel#48]
I'm currently using OSP version 5.4.3 and I want to use mysql version 8.0+ but it seem like OSP only has options for lower mysql version or mysql 8.0 for Win 10; is there anyway i can upgrade mysql to 8.0 on OSP for Win 11

**Comment by delphinpro** [comment]
Upgrade OSP to version 6.0

**Comment by OSPanel** [comment]
We do not support versions of the software below 6.0.
