### ISSUE TITLE
Как подключать Базу данных (MySQL Error!)?

### ISSUE THREAD

**Issue by mihadmitriev24445** [OSPanel/OpenServerPanel#5]
Как подключать Базу данных (MySQL Error!)?
Пол дня сижу и не пойму как теперь подключать свой файл sql?
Подскажите пожалуйста.

**Comment by delphinpro** [comment]
Такие вопросы следует задавать на форуме или в телеграм чате. Ссылка на чат есть где-то на форуме.
Здесь публикуются проблемы (ошибки) в работе комплекса, а не ваши проблемы.
